version: '3.8'

services:
  backend-service:
    # Construye la imagen desde el Dockerfile en el directorio actual
    build: .
    # Define un nombre de contenedor
    container_name: mi_backend_node
    # Mapea el puerto del contenedor al host (opcional, Nginx será el que acceda)
    ports:
      - "3000:3000"
    # Reinicia si falla
    restart: always
    # Variables de entorno si las necesitas (ejemplo)
    # environment:
    #   - NODE_ENV=production
    #   - DB_HOST=mi_db